Prevent TypeScript from emitting async helpers
They cause the following error when using ES Modules in Node:

import { __awaiter } from '../_virtual/_tslib.js';
         ^^^^^^^^^
SyntaxError: The requested module '../_virtual/_tslib.js' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.